project_id = "muoqzoypzravqkblzjis"

[functions.chat]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.booking-request]
verify_jwt = true
